runtime: python310
entrypoint: streamlit run repeated_calls_streamlit.py --server.port=$PORT --server.headless=true

instance_class: F2

env_variables:
  PYTHONUNBUFFERED: 'true'

handlers:
  - url: /.*
    script: auto
